### ISSUE TITLE
Have a trouble in step 4

### ISSUE THREAD

**Issue by jukilo123** [yiisoft/yii-swagger#68]
### What steps will reproduce the problem?
4
### What is the expected result?
I don't know if step 4 in wich file paste this code. I supose that the file is /project/config/web.php, but when i put the code fail, the error say  _**"Uncaught Error: Class "Yiisoft\\Definitions\\Reference"."**_
Please help me. 

Another question is, if i have in config/web.php 
```
'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'rules' => [
                    '<controller:\w+>/<id:\d+>'=>'<controller>/view',
               '<controller:\w+>/<action:\w+>/<id:\d+>'=>'<controller>/<action>',
               '<controller:\w+>/<action:\w+>'=>'<controller>/<action>'
            ],
```

where is the route to see swagger ui.
Thanks a lot for the support.

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 
| Operating system |

**Comment by rustamwin** [comment]
Are you using this package with Yii2?

**Comment by jukilo123** [comment]
Are you using this package with Yii2? Yes!

**Comment by samdark** [comment]
Well, that's not intended for Yii2. It is for Yii3.
